### ISSUE TITLE
Getting errors in linux.

### ISSUE THREAD

**Issue by plgonzalezrx8** [andrewbanchich/shreddit#106]
I'm getting the following error when trying to run in Red Hat, Rocky Linux and Fedora:

called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

And the following error in Ubuntu:

thread 'main' panicked at src/things/comment.rs:123:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("oauth.reddit.com")), port: None, path: "/api/editusertext", query: Some("raw_json=1"), fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Try again" })) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Was only able to get it running on Windows. Any help with this? I wish I knew better rust to help troubleshooting.

**Comment by mnpenner** [comment]
Same here. on WSL.

```
  2024-09-10T01:58:00.704591Z DEBUG  No shreddit.env config file found.
    at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shreddit-0.9.3/src/main.rs:37

thread 'main' panicked at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shreddit-0.9.3/src/access_token.rs:21:10:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.reddit.com")), port: None, path: "/api/v1/access_token", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by amitai** [comment]
Same here @ccampo133 - works 100% on MacOS, 0% on Ubuntu :(

**Comment by ccampo133** [comment]
I created a Go port that works on Linux if you're interested. It's not yet feature complete though https://github.com/ccampo133/shreddit-go

**Comment by andrewbanchich** [comment]
I use Ubuntu as well and it works fine for me. I'm on 24.04.

Please post details of your environment, like the specific Ubuntu version as well as the error you get. Otherwise there isn't much I can do.

**Comment by andrewbanchich** [comment]
I've updated the title of this issue to the specific error message. If anyone is getting a different error please create a separate issue.

**Comment by andrewbanchich** [comment]
Could someone who's getting this DNS error please post the specific command / config they're using (redacting any sensitive info like client secret / password)?

**Comment by ccampo133** [comment]
It's trivial to reproduce this with GitHub actions with the latest Ubuntu runner using a Docker image such as https://hub.docker.com/r/dmintz37/shreddit-dockerized.

I can post details later as I'm on my mobile at the moment but it should be fairly self explanatory. Just create a workflow to run that image and you'll see the error.

**Comment by amitai** [comment]
> Could someone who's getting this DNS error please post the specific command / config they're using (redacting any sensitive info like client secret / password) as well as the shreddit version?

Shreddit version 0.9.3
Ubuntu 22.04.5 LTS

Command:
```
./shreddit --username [USERNAME] --password [PASSWORD] --client-id [CLIENTID] --client-secret [SECRET]
```

Output:
```
thread 'main' panicked at /home/[USERNAME]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shreddit-0.9.3/src/things/post.rs:168:10:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
