### ISSUE TITLE
Immediate crash when running the Windows binary 

### ISSUE THREAD

**Issue by bhark** [andrewbanchich/shreddit#36]
Running the latest binary release (0.7.0) results in an immediate crash. Here's the verbose stacktrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("data did not match any variant of untagged enum AccessTokenResponse", line: 0, column: 0) }', src\access_token.rs:22:10
stack backtrace:
   0:     0x7ff65e833ca0 - std::backtrace_rs::backtrace::dbghelp::trace::h0cbe98da16679aac
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace/dbghelp.rs:98:5
   1:     0x7ff65e833ca0 - std::backtrace_rs::backtrace::trace_unsynchronized::hb434b45930b80e34
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:     0x7ff65e833ca0 - std::sys_common::backtrace::_print_fmt::h96c3729db5e2a8a1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common/backtrace.rs:65:5
   3:     0x7ff65e833ca0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbf171bd7f0118a33
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common/backtrace.rs:44:22
   4:     0x7ff65e8944ab - core::fmt::write::hb22cdfc2fa5ec795
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\fmt/mod.rs:1208:17
   5:     0x7ff65e826445 - std::io::Write::write_fmt::head66d9b1394f42d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\io/mod.rs:1682:15
   6:     0x7ff65e8339f4 - std::sys_common::backtrace::_print::heb838a6573dc6674
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common/backtrace.rs:47:5
   7:     0x7ff65e8339f4 - std::sys_common::backtrace::print::hf6ba081f1eb2c6e7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common/backtrace.rs:34:9
   8:     0x7ff65e836cbf - std::panicking::default_hook::{{closure}}::h93ea785abbbe90bf
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:267:22
   9:     0x7ff65e836993 - std::panicking::default_hook::h90332eef4943d9ce
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:286:9
  10:     0x7ff65e837603 - std::panicking::rust_panic_with_hook::hf9b5b9ac2430bc03
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:688:13
  11:     0x7ff65e837376 - std::panicking::begin_panic_handler::{{closure}}::he3e86f98d9b628f1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:579:13
  12:     0x7ff65e8347cf - std::sys_common::backtrace::__rust_end_short_backtrace::had7e7e5c444d2c2c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common/backtrace.rs:137:18
  13:     0x7ff65e837080 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:575:5
  14:     0x7ff65e890cc5 - core::panicking::panic_fmt::h421bf8d6cb47d0bf
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src/panicking.rs:64:14
  15:     0x7ff65e891296 - core::result::unwrap_failed::h7d46c234080deb8e
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src/result.rs:1791:5
  16:     0x7ff65e36b567 - shreddit::main::{{closure}}::h1b55403d6eb7de88
  17:     0x7ff65e353341 - tokio::runtime::scheduler::current_thread::Context::enter::hf2fde053ce164ec9
  18:     0x7ff65e3742b0 - tokio::macros::scoped_tls::ScopedKey<T>::set::h542e1d00d3dab19d
  19:     0x7ff65e352fd9 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h369e8cd262556650
  20:     0x7ff65e3896df - tokio::runtime::runtime::Runtime::block_on::h47aebc2d39d4d308
  21:     0x7ff65e31b4e0 - shreddit::main::h6250ab3fb126cda9
  22:     0x7ff65e300b26 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ea2dfc74adc8cc3
  23:     0x7ff65e31ff8c - std::rt::lang_start::{{closure}}::he82dffa03006e9e9
  24:     0x7ff65e8185e5 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h744a7898f6b57c9d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops/function.rs:606:13
  25:     0x7ff65e8185e5 - std::panicking::try::do_call::hacef15c93887bb9b
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:483:40
  26:     0x7ff65e8185e5 - std::panicking::try::h4c575fe78cd5baa2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:447:19
  27:     0x7ff65e8185e5 - std::panic::catch_unwind::h02c0d4967d414c4d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panic.rs:137:14
  28:     0x7ff65e8185e5 - std::rt::lang_start_internal::{{closure}}::h6de5ec9aa31df30b
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/rt.rs:148:48
  29:     0x7ff65e8185e5 - std::panicking::try::do_call::h2a585e8572d2bce7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:483:40
  30:     0x7ff65e8185e5 - std::panicking::try::hb6cd518eaad0a679
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panicking.rs:447:19
  31:     0x7ff65e8185e5 - std::panic::catch_unwind::ha20eca80b62d7156
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/panic.rs:137:14
  32:     0x7ff65e8185e5 - std::rt::lang_start_internal::haf6dd254fb13f778
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src/rt.rs:148:20
  33:     0x7ff65e31b5ed - main
  34:     0x7ff65e2f1445 - __tmainCRTStartup
  35:     0x7ff65e2f1146 - mainCRTStartup
  36:     0x7ffa46e426bd - <unknown>
  37:     0x7ffa4806dfb8 - <unknown>
```

**Comment by andrewbanchich** [comment]
I just released [`0.7.1`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.7.1) which should log the response instead of panicking. Could you try that and post the response?
