### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by dmintz7** [andrewbanchich/shreddit#44]
I've been running this for a week or two now but just started receiving this error today.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/shreddit-0.7.1/src/access_token.rs:23:10
stack backtrace:
   0:     0x5625289aea3a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5625289aea3a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5625289aea3a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5625289aea3a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5625289d3e9e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x5625289aba75 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x5625289ae805 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5625289ae805 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5625289affbf - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x5625289afcfb - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x5625289b0568 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x5625289b0469 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:     0x5625289aeea6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x5625289b0172 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x56252862c173 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x56252862c623 - core::result::unwrap_failed::hdff5465d74574b44
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
  16:     0x562528668f96 - shreddit::main::{{closure}}::h6e82294403626d58
  17:     0x56252869bdc1 - tokio::runtime::scheduler::current_thread::Context::enter::h47086dc8a0c5d187
  18:     0x5625286a55e2 - tokio::macros::scoped_tls::ScopedKey<T>::set::hc463bd22aa67b49c
  19:     0x56252869ba08 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::ha59e35b0f1a5af80
  20:     0x562528661716 - tokio::runtime::runtime::Runtime::block_on::h473cdb0b0417b6ab
  21:     0x562528640cb5 - shreddit::main::hd76dcd5dafc89bdb
  22:     0x5625286568e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha006b79e85a8313f
  23:     0x56252864b1c9 - std::rt::lang_start::{{closure}}::h5ad75d9b66483ea3
  24:     0x5625289a701c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  25:     0x5625289a701c - std::panicking::try::do_call::hce04e543bb1f4cbb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  26:     0x5625289a701c - std::panicking::try::h3342dd4e1f680968
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  27:     0x5625289a701c - std::panic::catch_unwind::h148ce1e59ac0cee7
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  28:     0x5625289a701c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  29:     0x5625289a701c - std::panicking::try::do_call::h7caaaeaf9401650b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  30:     0x5625289a701c - std::panicking::try::he7d15285746cbbc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  31:     0x5625289a701c - std::panic::catch_unwind::h89fb4f50c0301fe0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  32:     0x5625289a701c - std::rt::lang_start_internal::h078acd489417d3c1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  33:     0x562528640d95 - main
  34:     0x7f8d09aec09b - __libc_start_main
  35:     0x56252862c7ba - _start
  36:                0x0 - <unknown>
```

**Comment by polyurethanegoose** [comment]
I've got the same error. It looks like there are two issues at the same time:

1. There's still some problem with deserialization mentioned in #37 which is why we do not get proper error logged - minor problem.
2. Reddits API has some issues with himself (probably?) Even proper requests with curl like:
```
curl \
  -X POST \
  -d 'grant_type=password&username=<USER>&password=<PASSWORD \
  -u "<CLIENT_ID>:<CLIENT_SECRET>" \
  https://www.reddit.com/api/v1/access_token
```
... are returning  `{"error": "invalid_grant"}` which should be bull*** because `invalid_grant` should be response to only `grant_type=authorization_code` when parameter `code=<CODE>` is invalid (according to [this old docs](https://github.com/reddit-archive/reddit/wiki/OAuth2#retrieving-the-access-token)) and shreddit `uses grant_type=password`

**Comment by polyurethanegoose** [comment]
Ok, this is my final post. I've tried to look around and try to figure out things. This is my first time debugging issues with Rust. For start I've tried to figure out a way to fix issues with removing posts (running _shreddit_ with argument `--thing-types "posts"`)

I was able to (_probably_?) fix main issue by adding the `User-Agent` header even on HTTP GET. Which is totally strange. Then I've got THE SAME error (unwrap... etc.) in the _src/things/post.rs_ file somewhere around "Fetching post..." (i don't remember right now nor saved this error) and fixed that one with yet another "User-Agent" header on HTTP GET. It looks like Reddits API became really allergic to requests without UA or with common names in UA (my tests with cURL were rate-limited very fast)

So, my diff looks like this:
```diff
--- a/src/access_token.rs
+++ b/src/access_token.rs
@@ -15,6 +15,7 @@ pub async fn new_access_token(args: &Config, client: &Client) -> Result<String,
         .post("https://www.reddit.com/api/v1/access_token")
         .form(&params)
         .basic_auth(&args.client_id, Some(&args.client_secret))
+        .header("User-Agent", "ShredditRustClient")
         .send()
         .await
         .unwrap()
diff --git a/src/things/post.rs b/src/things/post.rs
index 24b8f2c..eb232fd 100644
--- a/src/things/post.rs
+++ b/src/things/post.rs
@@ -154,6 +154,7 @@ pub async fn list(client: &Client, username: &str) -> impl Stream<Item = Post> {

             let res: PostRes = client
         .get(&uri)
+        .header("User-Agent", "ShredditRustClient")
         .send()
         .await
         .unwrap()
```
This lead me to point where application started to run properly but then I've got following things in logs:
```
  2023-05-04T01:04:24.130402Z  INFO  Shredding Posts...
    at src/main.rs:93

  2023-05-04T01:04:24.130681Z  INFO  Fetching posts...
    at src/things/post.rs:138
    in list

  2023-05-04T01:04:24.602304Z ERROR  {"data":{"after":null,"before":null,"children":[{"data":{"all_awardings":[],"allow_live_comments":false,"approved_at_utc":null,"approved_by":null,"archived":false,"author":
  
  (... it is whole JSON from https://www.reddit.com/user/<MY_USERNAME>/submitted.json ...)
  
ull,"visited":false,"whitelist_status":null,"wls":null},"kind":"t3"}],"dist":3,"geo_filter":"","modhash":""},"kind":"Listing"}:#?
    at src/things/post.rs:183

  2023-05-04T01:04:24.604285Z  INFO  Completed shredding Posts
    at src/main.rs:130

  2023-05-04T01:04:24.604370Z  INFO  Completed shredding [Posts]
    at src/main.rs:133
```
It looks like it is stopping on `PostRes::Error(e)` (line 182) and i literally have no idea why.

**Comment by andrewbanchich** [comment]
Great finds @polyurethanegoose ! Thank you for this!

I'll make an update as soon as I have some free time (unless you'd like to make a PR).

**Comment by andrewbanchich** [comment]
Fixed both issues in [`0.7.2`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.7.2). Thanks again @polyurethanegoose

**Comment by dmintz7** [comment]
It is working again. Thank you @andrewbanchich @polyurethanegoose.

**Comment by andrewbanchich** [comment]
If you run it again does it work? The errors makes me think there was a bad internet connection so the request failed.

**Comment by chrisoffner** [comment]
It happens after a while every time I run it.

**Comment by chrisoffner** [comment]
Here's the latest error message.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Error(UnequalLengths { \
    pos: Some(Position { \
        byte: 9759,
        line: 26, record: 26
    }), \
    expected_len: 10,
    len: 11 \
})',
src/sources/gdpr.rs:17:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by andrewbanchich** [comment]
@chrisoffner Could you open a different issue for this? It's not the same error as this issue.
