### ISSUE TITLE
Panic while running in GDPR mode

### ISSUE THREAD

**Issue by FlareHeart** [andrewbanchich/shreddit#82]
I was running this in GDPR mode because I have a 14 year old reddit account that I'm trying to purge, and it ran for about 18 hours before panicking with the below error. I've set it to run again so I'll come back if it panics again at the same place. 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 2, column: 1) }', src\things\comment.rs:126:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by aprilmarikko** [comment]
Also having this issue

**Comment by aprilmarikko** [comment]
thread 'main' panicked at C:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\shreddit-0.9.3\src\things\post.rs:168:10:

called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
